# Generated by Django 5.1.7 on 2025-04-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('heatmap', '0001_initial'), ('heatmap', '0002_assalto_type'), ('heatmap', '0003_assalto_valid'), ('heatmap', '0004_location_alter_assalto_location'), ('heatmap', '0005_alter_location_rua'), ('heatmap', '0006_neighborhood_rename_numero_location_number_and_more'), ('heatmap', '0007_alter_location_neighborhood')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='heatmap.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Robbery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('a', 'assalto'), ('f', 'furto')], default='a', max_length=1)),
                ('is_valid', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robberies', to='heatmap.location')),
            ],
        ),
    ]
