# Generated by Django 5.1.7 on 2025-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assalto',
            name='type',
            field=models.CharField(choices=[('a', 'assalto'), ('f', 'furto')], default='a', max_length=1),
        ),
    ]
